apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-argoapp
  name: nginx-argoapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-argoapp
  type: NodePort
