apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-app
  namespace: prod3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  type: LoadBalancer
